services:
  app:
    container_name: project_zomboid_dedicated_server
    image: project-zomboid-dedicated-server:latest
    build: .
    env_file: .env
    ports:
      - 16261:16261/udp #Default Port
      #- 16262:16262/udp #Direct Connection
      - 27015:27015 #Rcon
    volumes:
      - ./data:/data
      - ./cache:/cache